# Generated by Django 3.1.7 on 2021-05-11 09:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('piece', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
                ('discountprice', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
