# Generated by Django 3.1.7 on 2021-05-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_pictures_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
