# Generated by Django 3.1.7 on 2021-05-05 14:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210501_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/cloud-image123/image/upload/v1619902588/cums8qvgrw9tkvzcaoyk.png', max_length=255, verbose_name='image'),
        ),
    ]
