# Generated by Django 3.1.7 on 2021-05-05 14:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_fooditems_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
