# Generated by Django 3.1.7 on 2021-05-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210505_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
