# Generated by Django 3.1.7 on 2021-05-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delete_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='slug',
            field=models.SlugField(default='m'),
        ),
    ]
