# Generated by Django 3.1.7 on 2021-05-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_fooditems_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='slug',
            field=models.SlugField(),
        ),
    ]
