# Generated by Django 3.1.7 on 2021-05-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210505_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='discountprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
