# Generated by Django 3.1.7 on 2021-05-05 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='name',
            new_name='fooditem',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
