# Generated by Django 3.1.7 on 2021-05-05 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210505_2337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
