# Generated by Django 3.1.7 on 2021-05-05 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_delete_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fooditem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.fooditems')),
            ],
        ),
    ]
