# Generated by Django 3.1.7 on 2021-05-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_orditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrdItem',
        ),
    ]
